version: '3'

services:
  api:
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"